spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Han2067813^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # ######################
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
server:
  port: 8081